-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 20:11:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitante` (
  `idsolicitante` INT NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `NOMBRES` VARCHAR(200) NULL,
  `APELLIDOPATERNO` VARCHAR(200) NULL,
  `APELLIDOMATERNO` VARCHAR(200) NULL,
  `ESTADOCIVIL` VARCHAR(1) NULL,
  PRIMARY KEY (`idsolicitante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`almacen` (
  `idalmacen` INT NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idalmacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `idproveedor` INT NOT NULL,
  `ruc` VARCHAR(11) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `email` VARCHAR(200) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordencompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordencompra` (
  `idOrdencompra` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `total` DECIMAL(9,2) NULL,
  `solicitante_idsolicitante` INT NOT NULL,
  `almacen_idalmacen` INT NOT NULL,
  `proveedor_idproveedor` INT NOT NULL,
  PRIMARY KEY (`idOrdencompra`),
  INDEX `fk_Ordencompra_solicitante_idx` (`solicitante_idsolicitante` ASC),
  INDEX `fk_Ordencompra_almacen1_idx` (`almacen_idalmacen` ASC),
  INDEX `fk_Ordencompra_proveedor1_idx` (`proveedor_idproveedor` ASC),
  CONSTRAINT `fk_Ordencompra_solicitante`
    FOREIGN KEY (`solicitante_idsolicitante`)
    REFERENCES `mydb`.`solicitante` (`idsolicitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordencompra_almacen1`
    FOREIGN KEY (`almacen_idalmacen`)
    REFERENCES `mydb`.`almacen` (`idalmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordencompra_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `mydb`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `presentacion` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `precio` DECIMAL(9,2) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalleorden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalleorden` (
  `iddetalle/producto` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `detelledeorden` VARCHAR(45) NULL,
  `precio` DECIMAL(9,2) NULL,
  `cantidad` INT NULL,
  `detalleordencol` VARCHAR(45) NULL,
  PRIMARY KEY (`iddetalle/producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detaleorden/producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detaleorden/producto` (
  `idDetaleorden` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NULL,
  `DETALLEORDEN_Producto` VARCHAR(45) NULL,
  `precio` DECIMAL(9,2) NULL,
  `Producto_idProducto` INT NOT NULL,
  `detalleorden_iddetalle/producto` INT NOT NULL,
  `Ordencompra_idOrdencompra` INT NOT NULL,
  PRIMARY KEY (`idDetaleorden`),
  INDEX `fk_Detaleorden/producto_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Detaleorden/producto_detalleorden1_idx` (`detalleorden_iddetalle/producto` ASC),
  INDEX `fk_Detaleorden/producto_Ordencompra1_idx` (`Ordencompra_idOrdencompra` ASC),
  CONSTRAINT `fk_Detaleorden/producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detaleorden/producto_detalleorden1`
    FOREIGN KEY (`detalleorden_iddetalle/producto`)
    REFERENCES `mydb`.`detalleorden` (`iddetalle/producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detaleorden/producto_Ordencompra1`
    FOREIGN KEY (`Ordencompra_idOrdencompra`)
    REFERENCES `mydb`.`Ordencompra` (`idOrdencompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
